name: Testes JUnit # Nome da pipe que aparece no Actions

on:
  push: # A pipe sempre é executada quando algo é mergeado na main
    branches: [ main ]
  pull_request: # A pipe sempre é executada quando é aberto MRs para a main
    branches: [ main ]

jobs:
  core: # É criado um job chamado build que vai rodar numa máquina virtual Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o Repositório na Máquina Virtual # Clona o repositório para a máquina virtual
        uses: actions/checkout@v3

      - name: Setup do Java 21 # Configura o Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build e Testes com Maven # Compila e da build no Projeto junto com a execução dos testes com Maven
        working-directory: backend/core # Entra na pasta do projeto do Core pra realizar os processos
        run: mvn clean verify -B
